development:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: rentmybike_dev
  pool: 5
  username: postgres
  password: 4arvrm4
  host: localhost
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  database: rentmybike_test
  pool: 5
  username: postgres
  password: 4arvrm4
  host: localhost
  port: 5432

# Add the below...

production:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: rentmybike_production
  pool: 5
  username: postgres
  password: 4arvrm4
